all: smithwatermanclient smithwatermanserver smithwatermanreference

smithwatermanclient: fasta.o socket.o clientsocket.o scoring.o smithwatermanclient.o 
	g++ fasta.o socket.o clientsocket.o scoring.o smithwatermanclient.o -o smithwatermanclient

smithwatermanserver: fasta.o alignment.o servercomm.o picodrv.o queryseqmanager.o refseqmanager.o scoring.o enginedispatchthread.o resultsreaderthread.o swthread.o serversocket.o socket.o smithwatermanserver.o
	g++ fasta.o alignment.o servercomm.o picodrv.o queryseqmanager.o refseqmanager.o scoring.o enginedispatchthread.o resultsreaderthread.o swthread.o serversocket.o socket.o smithwatermanserver.o -o smithwatermanserver -pthread

smithwatermanreference: fasta.o alignment.o scoring.o smithwatermanreference.o
	g++ fasta.o alignment.o scoring.o smithwatermanreference.o -o smithwatermanreference -lrt

fasta.o: fasta.cpp
	g++ -c fasta.cpp -g
	
socket.o: socket.cpp
	g++ -c socket.cpp -g
	
scoring.o: scoring.cpp
	g++ -c scoring.cpp -g

clientsocket.o: clientsocket.cpp
	g++ -c clientsocket.cpp -g

smithwatermanclient.o: smithwatermanclient.cpp
	g++ -c smithwatermanclient.cpp -g

alignment.o: alignment.cpp
	g++ -c alignment.cpp -g

servercomm.o: servercomm.cpp
	g++ -c servercomm.cpp -g
	
picodrv.o: picodrv.cpp
	g++ -c picodrv.cpp -g
	
queryseqmanager.o: queryseqmanager.cpp
	g++ -c queryseqmanager.cpp -g

refseqmanager.o: refseqmanager.cpp
	g++ -c refseqmanager.cpp -g

enginedispatchthread.o: enginedispatchthread.cpp
	g++ -c enginedispatchthread.cpp -g

resultsreaderthread.o: resultsreaderthread.cpp
	g++ -c resultsreaderthread.cpp -g

swthread.o: swthread.cpp
	g++ -c swthread.cpp -g

serversocket.o: serversocket.cpp
	g++ -c serversocket.cpp -g

smithwatermanserver.o: smithwatermanserver.cpp
	g++ -c smithwatermanserver.cpp -g

smithwatermanreference.o: smithwatermanreference.cpp
	g++ -c smithwatermanreference.cpp -g

clean:
	rm -rf *o smithwatermanclient smithwatermanserver smithwatermanreference

