all: refseqmanager_test 

refseqmanager_test: picodrv_stub.o alignment.o refseqmanager.o refseqmanager_test.o
	g++ picodrv_stub.o alignment.o refseqmanager.o refseqmanager_test.o -o refseqmanager_test

picodrv_stub.o: picodrv_stub.cpp
	g++ -c picodrv_stub.cpp

alignment.o: alignment.cpp
	g++ -c alignment.cpp

refseqmanager.o: refseqmanager.cpp
	g++ -c refseqmanager.cpp

refseqmanager_test.o: refseqmanager_test.cpp
	g++ -c refseqmanager_test.cpp

clean:
	rm -rf *o refseqmanager_test 

