all: resultsreaderthread_test

resultsreaderthread_test: alignment.o refseqmanager_stub.o queryseqmanager.o resultsreaderthread.o resultsreaderthread_test.o picodrv_stub.o
	g++ alignment.o refseqmanager_stub.o queryseqmanager.o resultsreaderthread.o resultsreaderthread_test.o picodrv_stub.o -o resultsreaderthread_test -pthread

alignment.o: alignment.cpp
	g++ -c alignment.cpp

refseqmanager_stub.o: refseqmanager_stub.cpp
	g++ -c refseqmanager_stub.cpp

queryseqmanager.o: queryseqmanager.cpp
	g++ -c queryseqmanager.cpp

resultsreaderthread.o: resultsreaderthread.cpp
	g++ -c resultsreaderthread.cpp

resultsreaderthread_test.o: resultsreaderthread_test.cpp
	g++ -c resultsreaderthread_test.cpp

picodrv_stub.o: picodrv_stub.cpp
	g++ -c picodrv_stub.cpp

clean:
	rm -rf *o resultsreaderthread_test

