all: smithwatermanreference

smithwatermanreference: fasta.o smithwatermanreference.o
	g++ fasta.o smithwatermanreference.o -o smithwatermanreference 

fasta.o: fasta.cpp
	g++ -c fasta.cpp -g
	
smithwatermanreference.o: smithwatermanreference.cpp
	g++ -c smithwatermanreference.cpp -g

clean:
	rm -rf *o smithwatermanreference

